### ISSUE TITLE
update revenge bro

### ISSUE THREAD

**Issue by womanburner** [revenge-mod/RevengeXposed#3]
the fuck is revenge even doing bro discord is getting more broken by the day and it was already broken, cant switch from stickers to emojis or gifs due to the switch bar being nonexistent, the plugin browser is broken as it has been for 500000 years and i havent seen a single update to revenge

**Comment by PalmDevs** [comment]
> cant switch from stickers to emojis or gifs due to the switch bar being nonexistent  
Stop using old UI, or just don't update to a newer version.

> the plugin browser is broken as it has been for 500000 years  
We did not develop or maintain the plugin.

**Comment by nexpid** [comment]
> the plugin browser is broken as it has been for 500000 years

News flash, you can [report an issue on my repo](https://github.com/nexpid/RevengePlugins/issues/new/choose), [message me](https://discord.com/users/853550207039832084) or [create a forum post in #support](https://discord.com/channels/1205207689832038522/1205211700744167465) (which [already exists](https://canary.discord.com/channels/1205207689832038522/1211658853675044864))
