### ISSUE TITLE
Work at your own pace bro

### ISSUE THREAD

**Issue by Bdogg202** [revenge-mod/RevengeXposed#4]
I fucking love what revenge is doing bro discord is working fine every day and it was already fine, I can switch from stickers to Emojis or gifs due to the interface working like normal, the plugin browser is a third party plugin that you have nothing to do with and nothing's broken yet so I don't need updates kiss me bro

**Comment by PalmDevs** [comment]
ok

**Comment by Ushie** [comment]
here's your kiss 😘
